# Generated by Django 4.2.7 on 2023-11-17 12:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicalRecords', '0002_alter_category_options_medicalrecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='medicalRecords',
            new_name='medicalRecord',
        ),
    ]
